apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba2
spec:
  selector:
    matchLabels:
      app: prueba2
  template:
    metadata:
      labels:
        app: prueba2
    spec:
      containers:
      - name: prueba2
        image: my-images/prueba2:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: prueba2
spec:
  selector:
    app: prueba2
  ports:
  - port: 4001
    targetPort: 3001
  type: LoadBalancer
        
