apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba1
spec:
  selector:
    matchLabels:
      app: prueba1
  template:
    metadata:
      labels:
        app: prueba1
    spec:
      containers:
      - name: prueba1
        image: my-images/prueba1:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: prueba1
spec:
  selector:
    app: prueba1
  ports:
  - port: 4000
    targetPort: 3000
  type: LoadBalancer
        
